- task: AzureWebApp@1
  inputs:
    azureSubscription: 'my-azure-connection'
    appName: 'linked-list-app'
    package: 'linkedlist.java'
    runtimeStack: 'JAVA|11'
    resourceGroupName: 'my-resource-group'
